import Head from "next/head";
import Image from "next/image";
import Script from "next/script";
import styles from "../styles/Home.module.css";
var b = "hello"
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Helping center</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <Script src="./Blogs/Hello.js"></Script>
      </Head>
      <nav className={styles.navmenu}>
          <ul>
            <li>
              <a href="/">Home</a>
            </li>
            <li>
              <a href="/">About</a>
            </li>
            <li>
              <a href="/">contect</a>
            </li>
            <li>
              <a href="/">Blogs</a>
            </li>
            <li>
              <a href="/">Help</a>
            </li>
          </ul>
        </nav>
      <main className={styles.main}>
        {/* <Script>
          alert("hello")
        </Script> */}
       
        <h1 className={styles.title}>Helping center</h1>
        <div className="Blog">{b}</div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
